client_id = "349481eaea3dac822c09936e0936d2e3"
application_url = "https://pixel-dpu5.onrender.com"
embedded = true
name = "pixel"

[access_scopes]
scopes = "read_customer_events,read_pixels,write_pixels"

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = ["app/scopes_update"]

[auth]
redirect_urls = [
  "https://pixel-dpu5.onrender.com/auth/callback",
  "https://pixel-dpu5.onrender.com/api/auth"
]

[build]
automatically_update_urls_on_dev = true
